/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoStudioRouteImport } from './routes/video-studio'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PolishRouteImport } from './routes/polish'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ImageStudioRouteImport } from './routes/image-studio'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VideoStudioRoute = VideoStudioRouteImport.update({
  id: '/video-studio',
  path: '/video-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PolishRoute = PolishRouteImport.update({
  id: '/polish',
  path: '/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStudioRoute = ImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/calendar': typeof CalendarRoute
  '/create': typeof CreateRoute
  '/image-studio': typeof ImageStudioRoute
  '/onboarding': typeof OnboardingRoute
  '/polish': typeof PolishRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/calendar': typeof CalendarRoute
  '/create': typeof CreateRoute
  '/image-studio': typeof ImageStudioRoute
  '/onboarding': typeof OnboardingRoute
  '/polish': typeof PolishRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/calendar': typeof CalendarRoute
  '/create': typeof CreateRoute
  '/image-studio': typeof ImageStudioRoute
  '/onboarding': typeof OnboardingRoute
  '/polish': typeof PolishRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/video-studio': typeof VideoStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assets'
    | '/calendar'
    | '/create'
    | '/image-studio'
    | '/onboarding'
    | '/polish'
    | '/reviews'
    | '/settings'
    | '/templates'
    | '/video-studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assets'
    | '/calendar'
    | '/create'
    | '/image-studio'
    | '/onboarding'
    | '/polish'
    | '/reviews'
    | '/settings'
    | '/templates'
    | '/video-studio'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assets'
    | '/calendar'
    | '/create'
    | '/image-studio'
    | '/onboarding'
    | '/polish'
    | '/reviews'
    | '/settings'
    | '/templates'
    | '/video-studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  CalendarRoute: typeof CalendarRoute
  CreateRoute: typeof CreateRoute
  ImageStudioRoute: typeof ImageStudioRoute
  OnboardingRoute: typeof OnboardingRoute
  PolishRoute: typeof PolishRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  VideoStudioRoute: typeof VideoStudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-studio': {
      id: '/video-studio'
      path: '/video-studio'
      fullPath: '/video-studio'
      preLoaderRoute: typeof VideoStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polish': {
      id: '/polish'
      path: '/polish'
      fullPath: '/polish'
      preLoaderRoute: typeof PolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-studio': {
      id: '/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof ImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  CalendarRoute: CalendarRoute,
  CreateRoute: CreateRoute,
  ImageStudioRoute: ImageStudioRoute,
  OnboardingRoute: OnboardingRoute,
  PolishRoute: PolishRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  VideoStudioRoute: VideoStudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
